[package]
name = "sudokuv2"
version = "0.1.0"
authors = ["Alexander von Mutius <amutius@boreus.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "*"

